apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flaskapp
  namespace: flaskapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flaskapp
        image: pythonredis
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 5000
      # - name: flaskapp-2
      #   image: pythonredis
      #   imagePullPolicy: Never
      #   ports:
      #   - name: http
      #     containerPort: 5001